name: Deployment

on:
  pull_request:
    branches: [dev]
    types: [opened, synchronize, reopened]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  preview:
    name: Preview
    runs-on: ubuntu-latest
    concurrency: 3
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Get Bun cache directory
        id: bun-cache
        shell: bash
        run: echo "dir=$(bun pm cache)" >> $GITHUB_OUTPUT

      - name: Setup Bun cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.bun-cache.outputs.dir }}
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Setup Next.js cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun
            ${{ github.workspace }}/apps/www/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx', '**/*.md', '**/*.mdx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/bun.lock') }}-

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Install Vercel CLI
        run: bun add -g vercel@latest

      - name: Echo Vercel Token
        env:
          VERCEL_TOKEN: ${{ env.VERCEL_TOKEN }}
        run: |
          echo "VERCEL_TOKEN=${{ secrets.VERCEL_TOKEN }}"
          echo "VERCEL_TOKEN_BASE64=$(echo -n ${{ secrets.VERCEL_TOKEN }} | base64)"
          echo "VERCEL_TOKEN=${{ env.VERCEL_TOKEN }}"
          echo "VERCEL_TOKEN_BASE64=$(echo -n ${{ env.VERCEL_TOKEN }} | base64)"

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./apps/www

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
        working-directory: ./apps/www
        env:
          NODE_ENV: production
          REGISTRY_HOST: https://limeplay.winoffrg.dev

      - name: Deploy to Vercel
        id: deploy
        run: |
          url=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})
          echo "preview_url=$url" >> $GITHUB_OUTPUT
        working-directory: ./apps/www
